google_project_id       = "fuchicorpkamila"
google_bucket_name      = "kamilakebere1078"
deployment_environment  = "qa"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json"